name: Build App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-26
    if: github.event.head_commit.author.email != '41898282+github-actions[bot]@users.noreply.github.com'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.app

      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid findutils sed coreutils make

      - name: Build
        run: |
          chmod +x Resources/Scripts/compile.release.mobile.ci.sh
          ./Resources/Scripts/compile.release.mobile.ci.sh "$(pwd)" "$(pwd)/Asspp.ipa"

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Asspp.ipa
          path: Asspp.ipa

      - name: Update SideStore Repo
        # Only run for pushes or internal PRs (not forked PRs)
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
        run: |
          chmod +x Resources/Scripts/update.sidestore.ci.sh 
          ./Resources/Scripts/update.sidestore.ci.sh "$(pwd)" "$(pwd)/Asspp.ipa" "${{ steps.upload.outputs.artifact-url }}"
